USE NIMBUS;

CREATE TABLE bucket(
    ID PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    BucketName VARCHAR(64) UNIQUE NOT NULL,
    CreatedAt BIGINT NOT NULL,
    UpdatedAt BIGINT NOT NULL,
    CreatedBy VARCHAR(32) NOT NULL,
    UpdatedBy VARCHAR(32) NOT NULL
) IF NOT EXISTS;