USE NIMBUS;

CREATE TYPE status AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED');

CREATE TABLE execution(
    ID PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    BucketID FOREIGN KEY NOT NULL,
    ObjectID FOREIGN KEY NOT NULL,
    Status status NOT NULL DEFAULT 'PENDING',
    StartedAt BIGINT NOT NULL DEFAULT (strftime('%s','now')),
    EndedAt BIGINT,
    CreatedAt BIGINT NOT NULL,
    UpdatedAt BIGINT NOT NULL,
    ExecutedBy VARCHAR(32) NOT NULL
    Success BOOLEAN NOT NULL DEFAULT FALSE
) IF NOT EXISTS;