USE NIMBUS;

CREATE TABLE objects(
    ID PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    BucketID FOREIGN KEY UNIQUE NOT NULL,
    KEY VARCHAR (64) UNIQUE NOT NULL,
    PREFIX VARCHAR(64) NOT NULL,
    Size BIGINT NOT NULL,
    CreatedAt BIGINT NOT NULL,
    UpdatedAt BIGINT NOT NULL,
    CreatedBy VARCHAR(32) NOT NULL,
    UpdatedBy VARCHAR(32) NOT NULL
) IF NOT EXISTS;